// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one

INSERT INTO feed_follows (id, feed_id, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, feed_id, user_id, created_at, updated_at
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	FeedID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

// The syntax for a sqlc query is like this->->name: {funcName} :{noOfRecordsToReturn}
// After defining your schema, go to your project root(where sqlc.yaml is) and use "sqlc generate" to generate the functions
// For {noOfRecordsToReturn} when you are not returning a query result, you use :exec, but if you return one or many records,
// you use :one or :many respectively
func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.FeedID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeedFollowsById = `-- name: DeleteFeedFollowsById :exec
DELETE FROM feed_follows 
WHERE id=$1 AND user_id=$2
RETURNING id, feed_id, user_id, created_at, updated_at
`

type DeleteFeedFollowsByIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFeedFollowsById(ctx context.Context, arg DeleteFeedFollowsByIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowsById, arg.ID, arg.UserID)
	return err
}

const getFeedFollowsByUserId = `-- name: GetFeedFollowsByUserId :many
SELECT id, feed_id, user_id, created_at, updated_at 
FROM feed_follows
WHERE user_id=$1
`

func (q *Queries) GetFeedFollowsByUserId(ctx context.Context, userID uuid.UUID) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
